name: Build Prod Image ARM

on:
  workflow_dispatch:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+rc[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+build[0-9]+'
      - '[0-9]+.[0-9]+rc[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}  # checkout current branch
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build ${{ github.ref_name }} Prod Image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: urganot/papermerge-raspberry:${{ github.ref_name }}-arm64
          file: docker/prod/Dockerfile
          platforms: linux/arm64
          build-args: AUTH_SERVER_TAG=0.9.0-arm64
#      - name: Docker Hub Description
#        uses: peter-evans/dockerhub-description@v3
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}
#          repository: papermerge/papermerge
#          readme-filepath: ./docker/prod/README.md
#          short-description: >
#            Papermerge is an open source document management system (DMS)
#             for digital archives
